services:
  postgres:
    image: postgres:15-alpine
    container_name: petgo_postgres
    restart: always
    environment:
      POSTGRES_DB: petgo
      POSTGRES_USER: apipetgouser
      POSTGRES_PASSWORD: password
    ports:
      - '5488:5432'
    volumes:
      - petgo_postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: petgo_adminer
    restart: always
    ports:
      - '5050:8080'
    depends_on:
      - postgres

volumes:
  petgo_postgres_data:
